// This file will be auto-generated by Supabase CLI.
// Run `pnpm supabase:types` (or `npm run supabase:types` / `yarn supabase:types`) to generate it.
// Make sure to replace YOUR_PROJECT_ID_HERE in package.json with your actual Supabase project ID.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          price: number;
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          price: number;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          payment_key: string;
          order_id: string;
          amount: number;
          status: "PENDING" | "DONE" | "CANCELED";
          product_id: string | null;
          user_id: string | null;
          payment_method: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          payment_key: string;
          order_id: string;
          amount: number;
          status: "PENDING" | "DONE" | "CANCELED";
          product_id?: string | null;
          user_id?: string | null;
          payment_method?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          payment_key?: string;
          order_id?: string;
          amount?: number;
          status?: "PENDING" | "DONE" | "CANCELED";
          product_id?: string | null;
          user_id?: string | null;
          payment_method?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
